# Generated by Django 6.0.3 on 2026-04-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(
                        default=datetime.datetime(2026, 4, 9, 20, 55, 45, 693810, tzinfo=datetime.timezone.utc),
                        help_text="Дата и время начало рассылки.",
                        verbose_name="Начала рассылки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Дата и время окончания рассылки.", verbose_name="Окончание рассылки"
                    ),
                ),
                ("status", models.CharField(default="Создана", max_length=10, verbose_name="Статус")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication", models.BooleanField(default=True, verbose_name="Признак публикации")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "mailing",
                "ordering": ["-created_at"],
                "permissions": [("can_unpublish_mailing", "Can unpublish mailing")],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                ("status", models.CharField(max_length=12, verbose_name="Статус")),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервиса.")),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "db_table": "mailing_attempts",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject_letter",
                    models.CharField(help_text="Укажите тему письма", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "body_letter",
                    models.TextField(
                        blank=True, help_text="Укажите содержание письма", null=True, verbose_name="Тело письма"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "db_table": "message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Адрес электронной почты")),
                ("first_name", models.CharField(help_text="Укажите имя!", max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(help_text="Укажите фамилию!", max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Не обязательно к заполнению!",
                        max_length=50,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Комментарий", null=True, verbose_name="Комментарий"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Получатель рассылок",
                "verbose_name_plural": "Получатели рассылок",
                "db_table": "recipient",
                "ordering": ["-created_at"],
            },
        ),
    ]
